export const queryKeys = {
    players: "players",
    playersWithCharacters: "playersWithCharacters",
    playersWithoutCharacters: "playersWithoutCharacters",
    playersSummary: "playersSummary",
    characters: "characters",
    character: "character",
    characterGameInfo: "characterGameInfo",
    rosterSummary: "rosterSummary",
    raidProgression: "raidProgression",
    droptimizers: "droptimizers",
    loots: "loots",
    raidSessions: "raidSessions",
    raidSession: "raidSession",
    items: "items",
    bosses: "bosses",
    settings: "settings",
    bisList: "bisList",
    lootRecapSessions: "lootRecapSessions",
    lootRecap: "lootRecap",
} as const
